# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 1
/control/macroPath $HOME/B1-b/kapis.mac
/run/verbose 1
/event/verbose 1
/tracking/verbose 1

/control/foreach kapis.mac eKin "3000"
#
#
# gamma 6 MeV to the direction (0.,0.,1.)
#
/gun/particle gamma
#
#/gun/energy 25 keV
#
#/run/beamOn 100000
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
#/gun/particle proton
#/gun/energy 210 MeV
#/tracking/verbose 2
#
#/run/beamOn 1
